### ISSUE TITLE
chore request: drop the hard dependencies on nestjs packages

### ISSUE THREAD

**Issue by micalevisk** [muhammetozendev/typeorm-transaction-module#1]
Hi!

I believe that those dependencies on `@nestjs/` should be moved to `peerDependencies` instead, as this package is supposed to be a nestjs lib, right?

https://github.com/muhammetozendev/typeorm-transaction-module/blob/e92dfd7068862905a13a51a05d68b6e527756415/package.json#L13-L16

as of now, if we install `typeorm-transaction-module` in a nestjs project, the app will load 2 modules of each `@nestjs/*` package if somehow our app is using another version of nestjs that doesn't aligns with yours - which may lead to module dependency issues as described [here on nestjs docs](https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error)

---

Also, I didn't understand why the package depends on `@nestjs/platform-express` since it seems not to be used anywhere here:
![image](https://github.com/muhammetozendev/typeorm-transaction-module/assets/13461315/6bac94ef-1173-4e65-a2ec-dcbf27e517bb)

:thinking:

**Comment by muhammetozendev** [comment]
Hi @micalevisk 
I actually had created the project with CLI and did not check dependencies properly. I just fixed dependencies. Thanks for pointing it out.
